In [2]:
# Libraries needed
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [3]:
# Environment
env = gym.make('FrozenLake-v0')

In [4]:
# Environment variables
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
exploration_decay_rate = 0.01
max_exploration_rate = 1
min_exploration_rate = 0.01

In [5]:
# Creating Q table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n


q_table = np.zeros((state_space_size,action_space_size))

In [6]:
#  Values in Q table
print(q_table)
print('Shape of Q table:',q_table.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Q table: (16, 4)


In [7]:
# Used to observe the rewards of each episode later
rewards_all_episodes = []


# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        # Take new action
        # Update Q-table
        # Set new state
        # Add new reward        

    # Exploration rate decay   
    # Add current episode reward to total rewards list


In [8]:
# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    done = False
    reward_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_threshold_rate = random.uniform(0,1)
        if exploration_threshold_rate > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        #  Taking action
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Setting new state
        state = new_state
        
        # Reward added
        reward_current_episode += reward
        
        if done == True:
            break
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    # Adding rewards
    rewards_all_episodes.append(reward_current_episode)

        
            
        

In [9]:
sum(rewards_all_episodes)

3265.0

In [11]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(sum(r))
    print(count, ": ", str(sum(r/1000)))
    count += 1000



********Average reward per thousand episodes********

154.0
1000 :  0.1540000000000001
222.0
2000 :  0.22200000000000017
193.0
3000 :  0.19300000000000014
231.0
4000 :  0.23100000000000018
184.0
5000 :  0.18400000000000014
190.0
6000 :  0.19000000000000014
212.0
7000 :  0.21200000000000016
533.0
8000 :  0.5330000000000004
692.0
9000 :  0.6920000000000005
654.0
10000 :  0.6540000000000005


In [12]:
#printing Q-table
print('*******************Printing Q-table*********************')
print(q_table)

*******************Printing Q-table*********************
[[0.52738514 0.42015903 0.44182789 0.45833264]
 [0.11687072 0.10531179 0.10922431 0.36377051]
 [0.15830054 0.16757406 0.23170899 0.18951989]
 [0.11459051 0.1272281  0.13041628 0.22183399]
 [0.53517596 0.30603647 0.33286232 0.34422313]
 [0.         0.         0.         0.        ]
 [0.10609504 0.04787872 0.27557012 0.08028984]
 [0.         0.         0.         0.        ]
 [0.32818813 0.46292105 0.42982867 0.57541512]
 [0.43819317 0.62987998 0.33813068 0.42949852]
 [0.64971032 0.25787454 0.24558381 0.16417942]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.31218756 0.46105232 0.75131658 0.42036867]
 [0.70791242 0.90108755 0.71783484 0.72962565]
 [0.         0.         0.         0.        ]]


# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        # Take new action
        
        if done:
            if reward == 1:
                # Agent reached the goal and won episode
            else:
                # Agent stepped in a hole and lost episode            
            
        # Set new state
        
env.close()

In [107]:
# Watch the agent play
all_episode_actions = []
for episode in range(3):
    state = env.reset()
    done = False
    print('********Starting episode ',episode,' ********')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
       
        action = np.argmax(q_table[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            if reward == 1:
                print('Agent reached the goal and won the episode.', episode)
                time.sleep(1)
            else:
                print('Agent stepped in a hole and lost episode.', episode)
                time.sleep(1)
            clear_output(wait=True)
            break
        state = new_state
    all_episode_actions.append(current_episode_actions)
env.close()
        

  (Left)
SFFF
FHFH
FFFH
HFFG
Agent stepped in a hole and lost episode. 2


In [104]:
#env.reset()
#env.step(1)

(0, 0.0, False, {'prob': 0.3333333333333333})

In [33]:
all_episode_actions

[[0, 0, 0, 0, 3, 1, 0, 1, 1, 1, 2, 1],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  0,
  3,
  0,
  0,
  0,
  0,
  3,
  3,
  1,
  2,
  2,
  2,
  1,
  3,
  0,
  3,
  1,
  3,
  3,
  0,
  0,
  0,
  3,
  1,
  0,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  1,
  2,
  1,
  1,
  1,
  1,
  2,
  1,
  2,
  1,
  2,
  2,
  1,
  3,
  1,
  2,
  2,
  1,
  2,
  1,
  2,
  1,
  2,
  1],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  0,
  3,
  1,
  3,
  3,
  1,
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  3,
  1,
  2,
  1,
  3,
  1,
  3,
  1,
  0,
  1,
  3,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]]